# -*- coding: utf-8 -*-
"""request.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r082yo0pjor2B24XlfNjMtylXaHy4q7J
"""

import requests

# URL
url = 'http://localhost:5000/api/'

# Change the value of experience that you want to test
prediction = {
	'age' : 26, 
  'gender': 2, 
  'polyuria' : 0, 
  'polydipsia' : 0,
  'sudden_weight_loss' : 0,	
  'weakness' : 1,	
  'polyphagia' : 0,	
  'genital_thrush' : 0,	
  'visual_blurring' : 1, 
  'itching' : 1,
  'irritability' : 1, 	
  'delayed_healing' : 0,	
  'partial_paresis' : 1,
  'muscle_stiffness' : 0, 
  'alopecia' : 0, 
  'obesity'	: 0
}

r = requests.post(url,json=prediction)

print(r.json()