# -*- coding: utf-8 -*-
"""server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sS5JIOv0kfQc0Bq1t6OrBYyznjpzm8SQ
"""

import numpy as np
from flask import Flask, request, jsonify
import pickle
import tensorflow as tf

app = Flask(__name__)

model_load=pickle.load(open('model.pkl','rb'))

@app.route('/api/',methods=['POST'])
def predict():
    # Get the data from the POST request.
    data = request.get_json(force=True)

    # Make prediction using model loaded from disk as per the data.
    prediction = model_load.predict([[np.array(data['age', 'gender', 'polyuria', 'polydipsia',	'sudden_weight_loss',	'weakness',	'polyphagia',	'genital_thrush',	'visual_blurring', 'itching', 'irritability', 	'delayed_healing',	'partial_paresis',	'muscle_stiffness', 'alopecia', 'obesity'])]])

    # Take the first value of prediction
    output = prediction[40, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1]

    return jsonify(output)

if __name__ == '__main__':
    try:
        app.run(port=5000, debug=True)
    except:
        print("Server is exited unexpectedly. Please contact server admin.")

